In [14]:
import os
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv1D, Dense, Concatenate, TimeDistributed, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
import numpy as np
from helper_funcs import gen_samples
from scipy.fft import rfftfreq
import pickle

In [1]:
# First navigate to our directory
transfer_directory_path = os.path.join("Data", "synth_transfer_df.parquet")
general_directory_path = os.path.join("Data", "synth_general_df.parquet")
# Load the dataframes
synth_transfer_df = pd.read_parquet(transfer_directory_path)
synth_general_df = pd.read_parquet(general_directory_path)
# Concatenate (after making sure they share columns) and then reset indices
assert list(synth_transfer_df.columns) == list(synth_general_df.columns), "Column names do not match!"
df = pd.concat([synth_transfer_df, synth_general_df], axis=0)
df.reset_index(drop=True, inplace=True)

NameError: name 'os' is not defined

In [ ]:
# Split into train (70%) and temp (30%) with stratification
train_df, temp_df = train_test_split(
    df,
    test_size=0.3,
    stratify=df['species'],  # Stratify based on the 'species' column
    random_state=42
)

# Split temp into test (15%) and validation (15%)
test_df, val_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df['species'],  # Stratify again to maintain balance
    random_state=42
)

In [ ]:
# Prepare samples
X_train, y_train, mins_maxes_train, isolated_peaks_train = gen_samples(train_df)
X_test, y_test, mins_maxes_test, isolated_peaks_test = gen_samples(test_df)
X_val, y_val, mins_maxes_val, isolated_peaks_val = gen_samples(val_df)

In [6]:
import matplotlib as plt

# Check our bin labeling worked
spectrum = X_train[0]
f = rfftfreq(32768, 1/44100)

labels = y_train[0]
binary_peak_labels = y_train[:, 0]
indices = np.where(binary_peak_labels == 1)[0]
plt.plot(f, spectrum)
plt.scatter(f[indices], spectrum[indices], color='red')
plt.show()

NameError: name 'X_train' is not defined

In [ ]:
def weight_func(snr, k=3):
    return ((snr/k)**k) / (1 + (snr/k)**k)


def custom_loss(y_true, y_pred):
    """
    Custom loss function for (batch_size, N, 3):
    - Binary cross-entropy for the first output node.
    - MSE for the second and third output nodes, masked by the first node's true labels.
    - Each bin in each sample is weighted by f(SNR), where SNR is the 3rd node label.
    
    Args:
    y_true: Tensor of true labels, shape (batch_size, N, 3).
    y_pred: Tensor of predicted values, shape (batch_size, N, 3).
    
    Returns:
    A scalar tensor representing the combined loss.
    """

    # Mean squared error for the second and third nodes
    mse_loss_2 = tf.square(y_true[..., 1] - y_pred[..., 1])
    mse_loss_3 = tf.square(y_true[..., 2] - y_pred[..., 2])
    mse_loss = mse_loss_2 + mse_loss_3  # Shape (batch_size, N)

    # Mask the MSE loss where the first node's true label is 0
    mask = tf.cast(y_true[..., 0] > 0, tf.float32)  # Shape (batch_size, N)
    masked_mse_loss = mse_loss * mask  # Shape (batch_size, N)
    
    # Manually calculate binary cross-entropy for the first node
    epsilon = 1e-7  # Small constant to prevent log(0)
    y_pred_clipped = tf.clip_by_value(y_pred[..., 0], epsilon, 1.0 - epsilon)
    bce_loss = -(y_true[..., 0] * tf.math.log(y_pred_clipped) + (1 - y_true[..., 0]) * tf.math.log(1 - y_pred_clipped))  # Shape (batch_size, N)

    # Weighting each bin by weight_func(SNR), where SNR is the 3rd node label
    snr = y_true[..., 2]  # SNR is the 3rd node label, shape (batch_size, N)
    weights = tf.where(snr < 0, tf.ones_like(snr), weight_func(snr))  # If SNR < 0, weight is 1 (fully weight the BCE loss for non-peak bins), else apply weight_func
    print(weights)

    # Apply weights to the masked MSE loss
    weighted_mse_loss = masked_mse_loss * weights  # Shape (batch_size, N)
    
    # Apply weights to the BCE loss
    weighted_bce_loss = bce_loss * weights  # Shape (batch_size, N)

    # Average weighted MSE, BCE losses across bins (N) for each sample
    mean_mse_loss_per_sample = tf.reduce_mean(weighted_mse_loss, axis=1)  # Mean over N for shape (batch_size,)
    mean_bce_loss_per_sample = tf.reduce_mean(weighted_bce_loss, axis=1)

    # Combine and average across the batch
    total_loss = tf.reduce_mean(mean_bce_loss_per_sample + mean_mse_loss_per_sample)  # Mean over batch size

    return total_loss

def custom_accuracy(val_isolated_labels, val_predictions):
    M = val_isolated_labels.shape[0]
    assert M == val_predictions.shape[0], "Mismatch in number of samples!"
    current_best = 10000
    for thresh in [0.5, 0.6, 0.7, 0.8, 0.9]:
        val_predictions_snapped = (val_predictions > thresh).astype(int)
        for row in range(M):
            val_isolated_labels_row = val_isolated_labels[row, :]
            # We want to go along the snapped row, and mark what the current bin is (0 or 1).
            # We also store the first index and the current index
            # Every time the current index switches, we then check how many peaks were truly in that row 
            
        

class ValidationMetricCallback(tf.keras.callbacks.Callback):
    def __init__(self, validation_data, metric_name="val_custom_mae"):
        super().__init__()
        self.validation_data = validation_data
        self.metric_name = metric_name

    def on_epoch_end(self, epoch, logs=None):
        val_x, (val_y, val_isolated_labels) = self.validation_data  # Unpack extra labels
        val_predictions = self.model.predict(val_x, verbose=0)
        
        # Compute your custom metric (e.g., Mean Absolute Error)
        val_metric = custom_accuracy(val_isolated_labels, val_predictions)

        # Add the validation metric to logs
        logs[self.metric_name] = val_metric.numpy()

        print(f"Epoch {epoch + 1}: {self.metric_name} = {val_metric.numpy()}")


    


In [10]:
# Figure out how many bins our peaks are
f = rfftfreq(32768, 1/44100)
# HWFM (in bins) of a peak with a HWHM of 100Hz
bin_width = f[1] - f[0]
print(f"HWFM (in bins) of a peak with a HWHM of 100Hz: {200 / bin_width}")
print(f"HWFM (in bins) of a peak with a HWHM of 10Hz: {20 / bin_width}")
print(f"HWFM (in bins) of a peak with a HWHM of 3Hz: {6 / bin_width}")

HWFM (in bins) of a peak with a HWHM of 100Hz: 148.6077097505669
HWFM (in bins) of a peak with a HWHM of 10Hz: 14.86077097505669
HWFM (in bins) of a peak with a HWHM of 3Hz: 4.458231292517007


In [ ]:
# Define name for this model
model_version = "PP V1"

# Define the input length / number of frequency bins (N)
N = 8192

# Input layer
input_layer = Input(shape=(N, 1), name="Input")

# Inception-like layer with 1D convolutions
convs = []
# We'll base our kernel choices on the hwhm distribution of the peaks. 
# Thin peaks are in 3Hz-10Hz range --> 5-15 bins
# Wide peaks are in 10Hz-100Hz range --> 15-149 bins
# We choose filters at a range of scales, odd (to facilitate being cenetered around a peak)
# and we want more filters for the medium-small range since there are more peaks at this scale.
# Otherwise largely arbitrarily.
kernels = [(3, 4), (5, 8), (9, 16), (15, 32), (31, 32), (55, 32), (71, 16), (101, 8), (149, 4), (201, 2)]
for kernel_size, num_filters in kernels:
    convs.append(Conv1D(num_filters, kernel_size=kernel_size, activation='relu', padding='same', name=f"Conv_{kernel_size}")(input_layer))

# Concatenate the outputs of all convolutional layers
concat_layer = Concatenate(name="Inception_Concat")(convs)

# Time Distributed Dense Layers
td_dense64 = TimeDistributed(Dense(64, activation='relu'), name="Dense_64")(concat_layer)
td_dense32A = TimeDistributed(Dense(32, activation='relu'), name="Dense_32A")(td_dense64)
# bd_LSTM = Bidirectional(LSTM(16, return_sequences=True), name="LSTM")(td_dense32A)
# td_dense32B = TimeDistributed(Dense(32, activation='relu'), name="Dense_32B")(bd_LSTM)
td_dense32B = TimeDistributed(Dense(32, activation='relu'), name="Dense_32B")(td_dense32A)
td_dense16 = TimeDistributed(Dense(16, activation='relu'), name="Dense_16")(td_dense32B)

# Final layer with 3 outputs per input bin
output = TimeDistributed(Dense(3, activation=None), name="Output")(td_dense16)

# Define the model
model = Model(inputs=input_layer, outputs=output, name=model_version)

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss=custom_loss, metrics=["custom_accuracy"])

# Summary
model.summary()


Model: "PP V1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ Input (InputLayer)  │ (None, 8192, 1)   │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_3 (Conv1D)     │ (None, 8192, 4)   │         16 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_5 (Conv1D)     │ (None, 8192, 8)   │         48 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_9 (Conv1D)     │ (None, 8192, 16)  │        160 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_15 (Conv1D)    │ (None, 8192, 32)  │        512 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_31 (Conv1D)    │ (None, 8192, 32)  │      1,024 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_55 (Conv1D)    │ (None, 8192, 32)  │      1,792 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_71 (Conv1D)    │ (None, 8192, 16)  │      1,152 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_101 (Conv1D)   │ (None, 8192, 8)   │        816 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_149 (Conv1D)   │ (None, 8192, 4)   │        600 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Conv_201 (Conv1D)   │ (None, 8192, 2)   │        404 │ Input[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Inception_Concat    │ (None, 8192, 154) │          0 │ Conv_3[0][0],     │
│ (Concatenate)       │                   │            │ Conv_5[0][0],     │
│                     │                   │            │ Conv_9[0][0],     │
│                     │                   │            │ Conv_15[0][0],    │
│                     │                   │            │ Conv_31[0][0],    │
│                     │                   │            │ Conv_55[0][0],    │
│                     │                   │            │ Conv_71[0][0],    │
│                     │                   │            │ Conv_101[0][0],   │
│                     │                   │            │ Conv_149[0][0],   │
│                     │                   │            │ Conv_201[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_64            │ (None, 8192, 64)  │      9,920 │ Inception_Concat… │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_32A           │ (None, 8192, 32)  │      2,080 │ Dense_64[0][0]    │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ LSTM                │ (None, 8192, 32)  │      6,272 │ Dense_32A[0][0]   │
│ (Bidirectional)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_32B           │ (None, 8192, 32)  │      1,056 │ LSTM[0][0]        │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Dense_16            │ (None, 8192, 16)  │        528 │ Dense_32B[0][0]   │
│ (TimeDistributed)   │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Output              │ (None, 8192, 3)   │         51 │ Dense_16[0][0]  

 Total params: 26,431 (103.25 KB)

 Trainable params: 26,431 (103.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Define batch size, number of epochs, and patience
batch_size = 32
epochs = 15
patience = 3

weight_path=os.path.join("PP Weights", f"{model_version}.h5")


# Add callbacks for better training
callbacks = [
    ValidationMetricCallback(validation_data=(X_val, (y_val, isolated_peaks_val)), metric_name="val_custom_accuracy"),
    EarlyStopping(monitor="val_custom_accuracy", patience=patience, restore_best_weights=True, verbose=1),  # Stop if no improvement for 5 epochs
    ModelCheckpoint(weight_path, save_best_only=True, monitor='val_loss')  # Save the best model
]



# Train the model
history = model.fit(
    X_train,                # Training data
    y_train,                # Training labels
    validation_data=(X_val, y_val),  # Validation data
    epochs=epochs,        # Number of epochs
    batch_size=batch_size,  # Batch size
    callbacks=callbacks,    # Add callbacks for early stopping and checkpointing
    verbose=1               # Verbose output
)

with open(f'{model_version}_history.pkl', 'wb') as file:
    pickle.dump(history.history, file)

In [ ]:
# Evaluate the model on the test set
test_loss = model.evaluate(X_test, y_test, verbose=1)  # Verbose output for evaluation

print("Test Loss:", test_loss)

In [78]:
# Example data: batch_size=4, N=5, nodes=3
y_true = np.array([
    [[0, 0.5, 0.7], [0, 0.2, -1], [0, 10000, -1000], [0, 0.3, 10], [0, 0.1, 10]],  # Sample 1
    [[0, 0.6, 0.3], [1, 0.1, -1], [1, 0.3, 10], [0, 0.4, 10], [0, 0.7, 10]],  # Sample 2
    [[0, 0.4, 1.5], [1, 0.8, -1], [1, 0.6, 10], [1, 0.2, 10], [0, 0.9, 10]],  # Sample 3
    [[0, 0.5, 0.6], [0, 0.3, -1], [0, 0.7, 10], [1, 0.1, 10], [0, 0.8, 10]],  # Sample 4
])

y_pred = np.array([
    [[0.9, 0.6, 0.8], [0.9, 0.3, 0.5], [0.5, 100000, 1000], [0.7, 0.4, 0.6], [0.2, 0.1, 0.3]],  # Sample 1
    [[0.7, 0.5, 0.4], [0.9, 0.2, 0.3], [0.9, 0.4, 0.6], [0.6, 0.7, 0.9], [0.8, 0.7, 0.8]],  # Sample 2
    [[0.8, 0.4, 0.5], [0.9, 0.6, 0.8], [0.9, 0.7, 0.5], [0.9, 0.3, 0.6], [0.2, 0.9, 0.7]],  # Sample 3
    [[0.9, 0.4, 0.3], [0.9, 0.6, 0.8], [0.6, 0.9, 0.7], [0.9, 0.3, 0.5], [0.8, 0.7, 0.6]],  # Sample 4
])

# Convert to tensors
y_true_tensor = tf.convert_to_tensor(y_true, dtype=tf.float32)
y_pred_tensor = tf.convert_to_tensor(y_pred, dtype=tf.float32)

loss_value = custom_loss(y_true_tensor, y_pred_tensor)
print("Loss Value:", loss_value.numpy())

tf.Tensor(
[[1.2544345e-02 1.0000000e+00 1.0000000e+00 9.7370982e-01 9.7370982e-01]
 [9.9900097e-04 1.0000000e+00 9.7370982e-01 9.7370982e-01 9.7370982e-01]
 [1.1111111e-01 1.0000000e+00 9.7370982e-01 9.7370982e-01 9.7370982e-01]
 [7.9365084e-03 1.0000000e+00 9.7370982e-01 9.7370982e-01 9.7370982e-01]], shape=(4, 5), dtype=float32)
Loss Value: 18.277445
